[package]
name = "fb2epub"
version = "0.3.0"
edition = "2024"
description = "Converter from fb2 to epub"
license = "MIT"
repository = "https://github.com/KiberBomzh/fb2epub"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["fb2", "epub", "cli", "converter"]

[lib]
name = "fb2epub"
path = "src/lib/lib.rs"

[[bin]]
name = "fb2epub"
path = "src/main.rs"
required-features = ["pipe"]

[dependencies]
base64 = "0.22.1"
epub-builder = "0.8"
quick-xml = { version = "0.38.4", features = ["encoding"]}
tempfile = "3.24"
zip = { version = "6", optional = true }
indicatif = { version = "0.18.3", optional = true }
threadpool = { version = "1.8.1", optional = true }
lexopt = "0.3.2"

[features]
default = ["zip"]
pipe = []
cli = [ "dep:indicatif", "dep:threadpool", "pipe"]
zip = ["dep:zip", "cli"]
